version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
      nodejs: 18
    commands:
      - echo Upgrading pip...
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
      # Enable docker https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - echo We will build here...
      - export X=$(pwd)
      - cd frontend/
      - npm install
      - npm run build
      - cd $X
      - ls
      - env
      - testing/pipeline/assume-role.sh ${TESTING_PIPELINE_EXECUTION_ROLE} test-package
      - env
artifacts:
  files:
    - testing/pipeline/assume-role.sh
    - testing/pipeline/*
    #- frontend_test_app/public/**/*
